### ISSUE TITLE
Game crashes when you attempt to load toolbar while in cryopod.

### ISSUE THREAD

**Issue by WesternGamer** [viktor-ferenczi/toolbar-manager#5] opened 2021-12-19 23:47 UTC
I found an issue where attempting to load a toolbar would crash the game while in a cryopod.

**Comment by viktor-ferenczi** [comment] 2021-12-24 16:11
I've just tested it and could not reproduce the problem.

However, I see why it could have happened, because the cryopod's toolbar type is None.

The next release will disable the Toolbar Manager functionality for the cryopod to prevent the problem from happening.

**Comment by viktor-ferenczi** [comment] 2021-12-24 16:18
Fixed in #6

**Closed by viktor-ferenczi** 2021-12-24 16:18 UTC
